import pandas as pd
def extract_rfm(rawdata):
    '''The Custom ETL Transformer: We engineer a Python function that ingests raw transactional dictionaries and calculates Recency, Frequency, and Monetary metrics on the fly.
    '''
    user_df=pd.DataFrame(rawdata)

    #Filtering the on Quantity>0 Data as -Quantity is of Returned to avoid miss calculation of Monetary
    filter_df=user_df[user_df['Quantity']>0].copy()

    #Getting current date and Obtaining the last date of purchase of a customer and obtaining Recency
    current_date=pd.Timestamp.now()
    filter_df['InvoiceDate']=pd.to_datetime(filter_df['InvoiceDate'])
    recency=lambda x : (current_date- x.max()).days

    #Obtaining Total Revenue generated by each customer  
    filter_df['TotalPrice']=filter_df['Quantity']*filter_df['Price']

    #Calculating RFM 
    df_rfm=filter_df.groupby('Customer ID').agg( Recency=('InvoiceDate',recency),
                                              Frequency=('Invoice','nunique'),
                                              Monetary=('TotalPrice','sum') )
    rfm=df_rfm[['Recency','Frequency','Monetary']]
    return rfm